name: Codescalers
on:
  push:
    branch: [ development ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www2.codescalers.com
      uses: appleboy/ssh-action@master
      with:
        host: www2.codescalers.com
        username: webuser
        key: ${{ secrets.TF_SECRET }}
        port: 34022
        script: |
          cd /home/webuser/websites/www2/www-codescalers
          git log -1
          git pull
